spring:
  datasource:
    url: jdbc:mysql://hopper.proxy.rlwy.net:56141/railway?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: LlinqNrmSYHKhugqMcfWdWcROxEHauMK
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
